// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi8fnDOt_Z6ndcwlDkHc9F3Cw1VUxJH9E',
    appId: '1:762546431336:web:1ea062d0a78eefd9c322dd',
    messagingSenderId: '762546431336',
    projectId: 'housepal-e925f',
    authDomain: 'housepal-e925f.firebaseapp.com',
    storageBucket: 'housepal-e925f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBViFZx6VESzcU00ZW-o1qpfrREhRWcQ34',
    appId: '1:762546431336:android:72e2fe6b13873ee9c322dd',
    messagingSenderId: '762546431336',
    projectId: 'housepal-e925f',
    storageBucket: 'housepal-e925f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhEIAzOky4ZAubLFm9VY0rgMwITnJN0mo',
    appId: '1:762546431336:ios:83f6d5050cd42fe7c322dd',
    messagingSenderId: '762546431336',
    projectId: 'housepal-e925f',
    storageBucket: 'housepal-e925f.firebasestorage.app',
    iosBundleId: 'com.example.hs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhEIAzOky4ZAubLFm9VY0rgMwITnJN0mo',
    appId: '1:762546431336:ios:83f6d5050cd42fe7c322dd',
    messagingSenderId: '762546431336',
    projectId: 'housepal-e925f',
    storageBucket: 'housepal-e925f.firebasestorage.app',
    iosBundleId: 'com.example.hs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi8fnDOt_Z6ndcwlDkHc9F3Cw1VUxJH9E',
    appId: '1:762546431336:web:d13f0a37458d0f35c322dd',
    messagingSenderId: '762546431336',
    projectId: 'housepal-e925f',
    authDomain: 'housepal-e925f.firebaseapp.com',
    storageBucket: 'housepal-e925f.firebasestorage.app',
  );
}